import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { FunctionComponent } from "react";
import { Props } from "../interface/interfaces";
import { NavBar } from "../NavBar";
import styles from "./MainLayout.module.css";

export const MainLayout: FunctionComponent<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Etienne next </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>{children}</main>
    </>
  );
};
